package sigma.stark

import org.scalatest.funsuite.AnyFunSuite
import org.scalatest.matchers.should.Matchers
import sigma.stark.receipt.InnerReceipt

import scala.io.Source

/** Known-Answer-Test parity for the EIP-0045 verifyStark FRI verifier
  * ([[FriVerifier]]).
  *
  * Expected values come from EXTERNAL oracles — never from the Scala code
  * under test (oracle-parity rule):
  *
  *  - `stark-kats/fri_kat.tsv` (generated by `stark-kat/src/bin/fri_kat.rs`):
  *    synthetic FRI proofs over 0/1/2/3 fold rounds, produced by risc0-zkp
  *    1.2.6's own `prove::fri::fri_prove` (byte-asserted) with per-round
  *    `(pos, goal)` checkpoints from the prover's own evaluation buffers;
  *    every vector — positive AND negative — was replayed through
  *    risc0-zkp's own `Verifier::fri_verify` before emission.
  *  - `stark-kats/transcript_capture.tsv`: the recorded Fiat-Shamir
  *    transcript of the REAL devnet receipt (risc0-zkp 3.0.4 accepting
  *    run), replayed here from the FRI phase onward over the receipt's own
  *    seal (`proof_inner.bin`).
  */
class FriKatSpec extends AnyFunSuite with Matchers {

  // --------------------------------------------------------------------
  // Helpers
  // --------------------------------------------------------------------

  private def lines(resource: String): Seq[String] = {
    val is = getClass.getResourceAsStream(resource)
    require(is != null, s"missing KAT resource $resource — run stark-kat fri_kat generator")
    try Source.fromInputStream(is, "UTF-8").getLines().filterNot(_.startsWith("#")).toList
    finally is.close()
  }

  private def resourceBytes(resource: String): Array[Byte] = {
    val is = getClass.getResourceAsStream(resource)
    require(is != null, s"missing KAT resource $resource")
    try {
      val buf = new java.io.ByteArrayOutputStream()
      val chunk = new Array[Byte](8192)
      var n = is.read(chunk)
      while (n >= 0) {
        buf.write(chunk, 0, n)
        n = is.read(chunk)
      }
      buf.toByteArray
    } finally is.close()
  }

  /** Wire words are u32; parse via Long so values >= 2^31 round-trip into
    * bit-identical Ints.
    */
  private def words(s: String): Array[Int] =
    if (s.isEmpty) Array.empty[Int] else s.split(',').map(w => java.lang.Long.parseLong(w.trim).toInt)

  private def ext4(ws: Array[Int]): Ext4 = Ext4(ws(0), ws(1), ws(2), ws(3))

  // --------------------------------------------------------------------
  // fri_kat.tsv parsing
  // --------------------------------------------------------------------

  private case class FriCaseVec(
      name: String,
      degree: Int,
      queries: Int,
      initialCommit: Array[Int],
      finalOff: Int,
      proof: Array[Int],
      /** qck(q)(r) = (pos, goal) before round r; last entry = final-poly
        * comparison state.
        */
      qck: Vector[Vector[(Int, Ext4)]],
      badWords: Seq[(Int, Int)],
      truncates: Seq[Int],
      badGoals: Seq[Int])

  private case class FriKat(rouFwd: Array[Int], rouRev: Array[Int], cases: Seq[FriCaseVec])

  private lazy val kat: FriKat = {
    var rouFwd: Array[Int] = null
    var rouRev: Array[Int] = null
    var cases = Vector.empty[FriCaseVec]
    var cur: FriCaseVec = null
    var qck = Map.empty[(Int, Int), (Int, Ext4)]
    lines("/stark-kats/fri_kat.tsv").foreach { line =>
      if (line.startsWith("rou_fwd:")) rouFwd = words(line.stripPrefix("rou_fwd:"))
      else if (line.startsWith("rou_rev:")) rouRev = words(line.stripPrefix("rou_rev:"))
      else if (line.startsWith("case:")) {
        val p = line.stripPrefix("case:").split(',')
        cur = FriCaseVec(p(0), p(1).toInt, p(2).toInt, null, -1, null, Vector.empty,
          Vector.empty, Vector.empty, Vector.empty)
        qck = Map.empty
      } else if (line.startsWith("initial_commit:")) {
        cur = cur.copy(initialCommit = words(line.stripPrefix("initial_commit:")))
      } else if (line.startsWith("final_off:")) {
        cur = cur.copy(finalOff = line.stripPrefix("final_off:").toInt)
      } else if (line.startsWith("proof:")) {
        cur = cur.copy(proof = words(line.stripPrefix("proof:")))
      } else if (line.startsWith("qck:")) {
        val Array(qr, v) = line.stripPrefix("qck:").split(" -> ")
        val Array(q, r) = qr.split(',').map(_.trim.toInt)
        val vs = words(v)
        qck += ((q, r) -> ((vs(0), Ext4(vs(1), vs(2), vs(3), vs(4)))))
      } else if (line.startsWith("badword:")) {
        val p = line.stripPrefix("badword:").split(',')
        cur = cur.copy(badWords = cur.badWords :+ ((p(0).toInt, java.lang.Long.parseLong(p(1)).toInt)))
      } else if (line.startsWith("truncate:")) {
        cur = cur.copy(truncates = cur.truncates :+ line.stripPrefix("truncate:").toInt)
      } else if (line.startsWith("badgoal:")) {
        cur = cur.copy(badGoals = cur.badGoals :+ line.stripPrefix("badgoal:").toInt)
      } else if (line == "endcase") {
        val rPerQ = qck.keys.groupBy(_._1).map { case (q, ks) => q -> ks.map(_._2).max }
        val chains = (0 until cur.queries).toVector.map { q =>
          (0 to rPerQ(q)).toVector.map(r => qck((q, r)))
        }
        cases = cases :+ cur.copy(qck = chains)
        cur = null
      } else fail(s"unknown fri KAT line: ${line.take(60)}")
    }
    require(rouFwd != null && rouRev != null && cases.nonEmpty, "incomplete fri_kat.tsv")
    FriKat(rouFwd, rouRev, cases)
  }

  /** Mirror of the generator's `oracle_fri_ok` (same accept criterion, so
    * a Scala reject here corresponds 1:1 to an oracle-confirmed reject).
    * Inner convention shared with the generator: known position -> its
    * recorded round-0 goal, unknown position -> 0; `badGoal` makes the
    * q-th inner call return goal + 1.
    */
  private def replayOk(v: FriCaseVec, proof: Array[Int], badGoal: Option[Int]): Boolean = {
    val goalMap: Map[Int, Ext4] = v.qck.map(c => c.head._1 -> c.head._2).toMap
    val iop = new ReadIop(proof)
    iop.commit(v.initialCommit)
    var call = 0
    val inner: Int => Either[String, Ext4] = { pos =>
      var g = goalMap.getOrElse(pos, Ext4.Zero)
      if (badGoal.contains(call)) g = g + Ext4.One
      call += 1
      Right(g)
    }
    FriVerifier.friVerify(iop, v.degree, v.queries, inner) match {
      case Left(_) => false
      case Right(_) => iop.verifyComplete
    }
  }

  // --------------------------------------------------------------------
  // Constants parity
  // --------------------------------------------------------------------

  test("FRI roots-of-unity tables match risc0-core's own constants") {
    kat.rouFwd should have length 28
    kat.rouRev should have length 28
    FriVerifier.RouFwd shouldBe kat.rouFwd
    FriVerifier.RouRev shouldBe kat.rouRev
    // Spot-check the algebra the tables promise: RouFwd(k) has order 2^k
    // and RouRev(k) is its inverse.
    (0 to 27).foreach { k =>
      BabyBear.pow(FriVerifier.RouFwd(k), 1L << k) shouldBe 1
      BabyBear.mul(FriVerifier.RouFwd(k), FriVerifier.RouRev(k)) shouldBe 1
    }
  }

  test("FRI profile constants match the extracted circuit parameters") {
    val params = lines("/stark-kats/circuit_params.tsv")
      .filter(_.startsWith("param\t"))
      .map(_.split('\t'))
      .map(p => p(1) -> p(2))
      .toMap
    FriVerifier.Queries shouldBe params("queries").toInt
    FriVerifier.InvRate shouldBe params("inv_rate").toInt
    FriVerifier.FriFold shouldBe params("fri_fold").toInt
    FriVerifier.FriFoldPo2 shouldBe params("fri_fold_po2").toInt
    FriVerifier.FriMinDegree shouldBe params("fri_min_degree").toInt
  }

  // --------------------------------------------------------------------
  // Synthetic prover-built proofs (accept + per-round checkpoints)
  // --------------------------------------------------------------------

  test("FriVerifier replays prover-built FRI proofs across 0/1/2/3 fold rounds") {
    kat.cases.map(_.name) shouldBe
      Seq("deg256_r0", "deg4096_r1", "deg65536_r2", "deg262144_r3")
    kat.cases.foreach { v =>
      withClue(s"case ${v.name}: ") {
        // Round structure implied by the checkpoints must match the
        // protocol's fold recursion (degree/16 while degree > 256).
        var expRounds = 0
        var d = v.degree
        while (d > FriVerifier.FriMinDegree) { expRounds += 1; d /= FriVerifier.FriFold }
        v.qck.foreach(_.length shouldBe (expRounds + 1))

        val goalMap: Map[Int, Ext4] = v.qck.map(c => c.head._1 -> c.head._2).toMap
        val iop = new ReadIop(v.proof)
        iop.commit(v.initialCommit)
        var call = 0
        val inner: Int => Either[String, Ext4] = { pos =>
          withClue(s"query $call drawn position: ") { pos shouldBe v.qck(call)(0)._1 }
          call += 1
          Right(goalMap(pos))
        }
        val probe: FriVerifier.Probe = { (q, r, pos, goal) =>
          withClue(s"checkpoint q$q r$r: ") {
            val (expPos, expGoal) = v.qck(q)(r)
            pos shouldBe expPos
            goal shouldBe expGoal
          }
        }
        FriVerifier.friVerify(iop, v.degree, v.queries, inner, probe) shouldBe Right(())
        call shouldBe v.queries
        iop.verifyComplete shouldBe true
      }
    }
  }

  // --------------------------------------------------------------------
  // Oracle-confirmed rejects
  // --------------------------------------------------------------------

  test("FriVerifier rejects corrupted proof words (oracle-confirmed rejects)") {
    kat.cases.flatMap(_.badWords) should not be empty
    kat.cases.foreach { v =>
      v.badWords.foreach { case (pos, xor) =>
        val corrupted = v.proof.clone()
        corrupted(pos) ^= xor
        withClue(s"case ${v.name} badword $pos^$xor: ") {
          replayOk(v, corrupted, None) shouldBe false
        }
      }
    }
  }

  test("FriVerifier rejects truncated proofs (oracle-confirmed rejects)") {
    kat.cases.foreach { v =>
      v.truncates.foreach { keep =>
        withClue(s"case ${v.name} truncate $keep: ") {
          replayOk(v, v.proof.take(keep), None) shouldBe false
        }
      }
    }
  }

  test("FriVerifier rejects a wrong DEEP-ALI goal (oracle-confirmed rejects)") {
    kat.cases.flatMap(_.badGoals) should not be empty
    kat.cases.foreach { v =>
      v.badGoals.foreach { q =>
        withClue(s"case ${v.name} badgoal $q: ") {
          replayOk(v, v.proof, Some(q)) shouldBe false
        }
      }
    }
  }

  test("FriVerifier surfaces inner failures without reading further") {
    val v = kat.cases.head
    val iop = new ReadIop(v.proof)
    iop.commit(v.initialCommit)
    val res = FriVerifier.friVerify(iop, v.degree, v.queries, _ => Left("no goal"))
    res.isLeft shouldBe true
    res.left.get should include("no goal")
  }

  test("FriVerifier rejects an empty stream instead of throwing") {
    val iop = new ReadIop(Array.empty[Int])
    FriVerifier.friVerify(iop, 4096, 50, _ => Right(Ext4.Zero)).isLeft shouldBe true
  }

  // --------------------------------------------------------------------
  // REAL receipt: FRI phase replay from the recorded transcript
  // --------------------------------------------------------------------

  test("FriVerifier replays the REAL devnet receipt's FRI phase over its seal") {
    // The seal of the real receipt (the oracle-accepted proof stream).
    val seal = InnerReceipt.parse(resourceBytes("/stark-kats/proof_inner.bin")) match {
      case Right(InnerReceipt.Succinct(r)) => r.seal
      case other => fail(s"unexpected receipt parse: $other")
    }

    // Recorded transcript events, in execution order.
    val events: Seq[Array[String]] =
      lines("/stark-kats/transcript_capture.tsv").map(_.split('\t'))
    val ck: Map[String, String] =
      events.filter(e => e(0) == "ck" && e.length == 3).map(e => e(1) -> e(2)).toMap

    val po2 = ck("po2").toInt
    val totCycles = 1 << po2
    val domain = FriVerifier.InvRate * totCycles
    val queries = FriVerifier.Queries
    ck("seal_words").toInt shouldBe seal.length

    // ---- seal layout of the FRI phase (word offsets) ----
    // Pre-FRI reads: 33 (out + po2), four Merkle top rows (code/data/accum/
    // check, topSize 32 digests each), coeff_u (643 taps + 16 check ext
    // elems). The FRI commit phase then reads one 32-digest top row + the
    // final polynomial; each query reads the DEEP-ALI branches (accum 12 +
    // code 23 + data 128 + check 16 columns, each with a 15-digest path in
    // the 2^20-row trees) followed by the per-round FRI branches.
    def topSize(rows: Int): Int = {
      val layers = FriVerifier.log2Ceil(rows)
      var top = 0
      var i = 1
      while (i < layers && (1 << i) <= queries) { top = i; i += 1 }
      1 << top
    }
    val numTaps = 643 // recursion circuit tapset (circuit_taps.tsv)
    val preFri = 33 + 4 * topSize(domain) * 8 + (numTaps + 16) * 4

    var rounds = 0
    var deg = totCycles
    var dom = domain
    var commitWords = 0
    var perQueryFri = 0
    val roundRows = scala.collection.mutable.ArrayBuffer.empty[Int]
    while (deg > FriVerifier.FriMinDegree) {
      val rows = dom / FriVerifier.FriFold
      roundRows += rows
      commitWords += topSize(rows) * 8
      perQueryFri += 64 + (FriVerifier.log2Ceil(rows) - FriVerifier.log2Ceil(topSize(rows))) * 8
      rounds += 1
      deg /= FriVerifier.FriFold
      dom /= FriVerifier.FriFold
    }
    rounds shouldBe 3
    deg shouldBe 64 // final degree of the po2=18 receipt
    val innerWords =
      (12 + 23 + 128 + 16) +
        4 * (FriVerifier.log2Ceil(domain) - FriVerifier.log2Ceil(topSize(domain))) * 8
    val queriesStart = preFri + commitWords + 4 * deg
    // Layout self-check against the oracle-recorded stream length.
    queriesStart + queries * (innerWords + perQueryFri) shouldBe seal.length

    // ---- transcript state at FRI entry ----
    // Reads and the rng are independent state machines (reads never touch
    // the rng; draws never consume words), so advance the cursor in one
    // step and replay the recorded rng events in order: the first 3
    // random_ext_elem draws (poly_mix, z, fri_batch_mix) end the pre-FRI
    // phase.
    val iop = new ReadIop(seal)
    iop.readU32s(preFri).isDefined shouldBe true
    var extSeen = 0
    val eventIt = events.iterator
    while (extSeen < 3 && eventIt.hasNext) {
      val e = eventIt.next()
      e(0) match {
        case "mix" => iop.commit(words(e(1)))
        case "elem" => iop.randomElem() shouldBe e(1).toInt
        case "ext" =>
          iop.randomExtElem() shouldBe ext4(words(e(1)))
          extSeen += 1
        case "bits" => fail("query position drawn before the FRI phase")
        case _ => () // hash_* call logs and ck checkpoints: not rng events
      }
    }
    extSeen shouldBe 3

    // ---- recorded query positions + round-0 goals from the seal ----
    val positions = events.filter(_(0) == "bits").map(_(2).toInt)
    positions should have length queries
    val rows0 = roundRows(0)
    val goals: IndexedSeq[Ext4] = (0 until queries).map { q =>
      // The round-0 column opening of query q: the oracle-accepted verify
      // bound these wire words to the round-0 Merkle root and checked them
      // against its DEEP-ALI goal, so they ARE the expected goal. (The
      // round-0 goal comparison is therefore structural here; the
      // synthetic fri_kat cases pin it independently.)
      val off = queriesStart + q * (innerWords + perQueryFri) + innerWords
      val quot = positions(q) / rows0
      def canon(w: Int): Int = {
        withClue(s"query $q round-0 word: ") { (w >= 0 && w < BabyBear.P) shouldBe true }
        BabyBear.fromRaw(w)
      }
      Ext4(
        canon(seal(off + quot)),
        canon(seal(off + 16 + quot)),
        canon(seal(off + 32 + quot)),
        canon(seal(off + 48 + quot)))
    }

    // ---- the replay ----
    var q = 0
    val inner: Int => Either[String, Ext4] = { pos =>
      withClue(s"query $q drawn position: ") { pos shouldBe positions(q) }
      // The DEEP-ALI branch openings belong to the outer verifier; skip
      // exactly the words it would consume (branch reads never touch the
      // rng).
      iop.readU32s(innerWords).isDefined shouldBe true
      val g = goals(q)
      q += 1
      Right(g)
    }
    FriVerifier.friVerify(iop, totCycles, queries, inner) shouldBe Right(())
    q shouldBe queries
    iop.verifyComplete shouldBe true
  }
}
