package org.ergo.stark.field

import org.scalatest.funsuite.AnyFunSuite
import org.scalatest.matchers.should.Matchers

import scala.io.Source

/** Cross-validates #1116's `BabyBearField` against the EXTERNAL oracle
  * vectors in `core/jvm/src/test/resources/stark-kats/` (generated by
  * `stark-kat/` from risc0-core 1.2.6 — RISC0's own production field
  * implementation).
  *
  * This is independent of `sigma.stark.BabyBear`'s own parity suite: two
  * separately-written implementations agreeing with the same external
  * oracle is the strongest correctness signal available short of proofs.
  */
class BabyBearFieldOracleParitySpec extends AnyFunSuite with Matchers {

  private def cases: Seq[Array[String]] = {
    val is = getClass.getResourceAsStream("/stark-kats/babybear_ops.tsv")
    require(is != null, "missing KAT resource — run stark-kat/ generator")
    try Source.fromInputStream(is, "UTF-8").getLines()
      .filterNot(_.startsWith("#")).map(_.split('\t')).toList
    finally is.close()
  }

  test("#1116 BabyBearField matches risc0-core oracle vectors") {
    val cs = cases
    cs should not be empty
    cs.foreach { f =>
      val (a, b) = (f(0).toInt, f(1).toInt)
      withClue(s"a=$a b=$b: ") {
        BabyBearField.add(a, b) shouldBe f(2).toInt
        BabyBearField.sub(a, b) shouldBe f(3).toInt
        BabyBearField.mul(a, b) shouldBe f(4).toInt
        BabyBearField.neg(a) shouldBe f(5).toInt
      }
    }
  }

  test("#1116 BabyBearField inverse/pow match risc0-core oracle vectors") {
    cases.foreach { f =>
      val (a, b) = (f(0).toInt, f(1).toInt)
      withClue(s"a=$a b=$b: ") {
        if (f(6) != "-") BabyBearField.inv(a) shouldBe f(6).toInt
        BabyBearField.pow(a, b.toLong) shouldBe f(7).toInt
      }
    }
  }
}
